#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-$ROOT_DIR/out/demos}"

mkdir -p "$OUT_DIR"

run() {
  echo "+ $*"
  "$@"
}

echo "latent-ir demo pack output: $OUT_DIR"

run cargo run -- generate \
  --prompt "vast icy cathedral with long tail and soft highs" \
  --t60 12 \
  --channels stereo \
  --seed 1337 \
  --output "$OUT_DIR/cathedral_stereo.wav" \
  --json-analysis-out "$OUT_DIR/cathedral_stereo.analysis.json"

run cargo run -- generate \
  --prompt "industrial aircraft hangar, dark steel, long metallic decay" \
  --channels 7.2.4 \
  --seed 4242 \
  --output "$OUT_DIR/hangar_724.wav" \
  --json-analysis-out "$OUT_DIR/hangar_724.analysis.json"

run cargo run -- generate \
  --prompt "32-second dark cave" \
  --duration 32 \
  --sample-rate 384000 \
  --channels custom \
  --layout-json "$ROOT_DIR/examples/layouts/custom_16_0_circle_10m_origin_cartesian_only.json" \
  --source-x-m 0.0 --source-y-m 24.0 --source-z-m 2.0 \
  --listener-x-m 0.0 --listener-y-m 0.0 --listener-z-m 1.5 \
  --seed 9001 \
  --output "$OUT_DIR/dark_cave_16ch_384k.wav" \
  --json-analysis-out "$OUT_DIR/dark_cave_16ch_384k.analysis.json"

run cargo run -- morph \
  "$OUT_DIR/cathedral_stereo.wav" \
  "$OUT_DIR/hangar_724.wav" \
  --alpha 0.35 \
  --output "$OUT_DIR/morph_cathedral_hangar.wav"

cat > "$OUT_DIR/README.md" <<'EOF'
# latent-ir Demo Pack

This folder was generated by `scripts/generate_demo_pack.sh`.

Included artifacts:
- `cathedral_stereo.wav` + `cathedral_stereo.analysis.json`
- `hangar_724.wav` + `hangar_724.analysis.json`
- `dark_cave_16ch_384k.wav` + `dark_cave_16ch_384k.analysis.json`
- `morph_cathedral_hangar.wav`

Suggested social post workflow:
1. Audition each IR in your DAW or convolution host.
2. Share before/after render clips for the same dry source.
3. Include the exact command lines for reproducibility.

Metrics note:
- Analysis values are deterministic engineering estimates for v0.
- They are not standards-certified architectural acoustics metrology.
EOF

echo "Demo pack ready."
